name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: <your-project-id>

    - name: Configure gcloud CLI
      run: |
        gcloud config set project <your-project-id>
        gcloud config set app/cloud_build_timeout 1000

    - name: Build and Deploy to App Engine
      run: |
        gcloud app deploy --quiet
